# Site settings
title: Rory Little
description: Rory Little's website and blog
url: "oneorten.dev"

# User settings
user:
  name: Rory Little
  title: Graduate Student
  email: rorylit@gmail.com

thing:
  assetsdir: hello

social:
  twitter: _rorylittle
  github: rory-little
  linkedin: rorylittle

sass:
  sass_dir: _sass

markdown: kramdown
mathjax: true

